version: "3"
services:
  app:
    build: .
    environment:
      - DISPLAY=:0
    volumes:
      - .:/usr/src/app
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/video0:/dev/video0
    ports:
      - "8080:8080"
    tty: true
    entrypoint: ["python3", "app.py"]
